export enum QUERY_KEYS {
    "SUBSCRIPTION_STATUS" = "subscription-status",
    "USER" = "user",
    "ANALYTICS" = "Analytics",
    "ASSISTANTLISTS" = "assistantLitsts",
    "ASSISTANT" = "assistant",
    "KNOWLEDGE_BASE_LISTS" = "knowledge-base-lists",
    "KNOWLEDGE_BASE" = "knowledge-base",
    "KNOWLEDGE_BASE_FILES" = "knowledge-base-files",
    "PHONE_NUMBERS" = "phone-numbers",
    "PHONE_NUMBER" = "phone-number",
    "BATCH_CALLS" = "batch-calls",
    "CALL_HISTORY" = "call-history",
    "CALL_DETAILS" = "call-details",
    "BATCH_CALL_ANALYTICS" = "batch-call-analytics",
    "GOHIGHLEVEL_SHEETS" = "gohighlevel-sheets",
    "GOHIGHLEVEL_CONTACTS" = "gohighlevel-contacts",
    "TOOL" = "tool",
    "TOOL_LISTS" = "tool-lists"
}